//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gen_tb_BusesEventos
    {
        public int idBusEvento { get; set; }
        public Nullable<int> idVehiculo { get; set; }
        public Nullable<System.DateTime> fechaEvento { get; set; }
        public string nombreEvento { get; set; }
        public string evento { get; set; }
        public Nullable<decimal> velocidad { get; set; }
    
        public virtual Gen_tb_Vehiculo Gen_tb_Vehiculo { get; set; }
    }
}
