//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gen_tb_Vehiculo
    {
        public Gen_tb_Vehiculo()
        {
            this.Gen_tb_VehiculoDetalle = new HashSet<Gen_tb_VehiculoDetalle>();
            this.Gen_tb_Horometro = new HashSet<Gen_tb_Horometro>();
            this.Gen_tb_BusesDetalle = new HashSet<Gen_tb_BusesDetalle>();
            this.Gen_tb_BusesEventos = new HashSet<Gen_tb_BusesEventos>();
        }
    
        public int idVehiculo { get; set; }
        public string placa { get; set; }
        public Nullable<System.DateTime> fechaRegistroApi { get; set; }
        public int idFlota { get; set; }
        public Nullable<long> idVehiculoApi { get; set; }
        public string vin { get; set; }
    
        public virtual ICollection<Gen_tb_VehiculoDetalle> Gen_tb_VehiculoDetalle { get; set; }
        public virtual ICollection<Gen_tb_Horometro> Gen_tb_Horometro { get; set; }
        public virtual Gen_tb_Flota Gen_tb_Flota { get; set; }
        public virtual ICollection<Gen_tb_BusesDetalle> Gen_tb_BusesDetalle { get; set; }
        public virtual ICollection<Gen_tb_BusesEventos> Gen_tb_BusesEventos { get; set; }
    }
}
