//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gen_tb_BusesDetalle
    {
        public int idBusDetalle { get; set; }
        public Nullable<decimal> latitud { get; set; }
        public Nullable<decimal> longitud { get; set; }
        public Nullable<int> rumbo { get; set; }
        public Nullable<System.DateTime> fechaRegistroGPS { get; set; }
        public int idVehiculo { get; set; }
        public string estaTransmitido { get; set; }
        public Nullable<System.DateTime> fechaActualizacion { get; set; }
    
        public virtual Gen_tb_Vehiculo Gen_tb_Vehiculo { get; set; }
    }
}
