//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace EntitiesLayer
{
    public partial class Gen_tb_Flota
    {
        public Gen_tb_Flota()
        {
            this.Gen_tb_Vehiculo = new HashSet<Gen_tb_Vehiculo>();
        }
    
        public int idFlota { get; set; }
        public string nombreFlota { get; set; }
        public string usuario { get; set; }
        public string password { get; set; }
        public string activo { get; set; }
    
        public virtual ICollection<Gen_tb_Vehiculo> Gen_tb_Vehiculo { get; set; }
    }
    
}
