//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace EntitiesLayer
{
    public partial class Gen_tb_Horometro
    {
        public int idHorometro { get; set; }
        public Nullable<long> horometro { get; set; }
        public Nullable<System.DateTime> fechaInicio { get; set; }
        public Nullable<System.DateTime> fechaFin { get; set; }
        public int idVehiculo { get; set; }
    
        public virtual Gen_tb_Vehiculo Gen_tb_Vehiculo { get; set; }
    }
    
}
