//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace EntitiesLayer
{
    public partial class viewReporteHorometro
    {
        public int idHorometro { get; set; }
        public string usuario { get; set; }
        public string nombreFlota { get; set; }
        public string vin { get; set; }
        public Nullable<System.DateTime> fechaInicio { get; set; }
        public string fechaInicioFormato { get; set; }
        public Nullable<System.DateTime> fechaFin { get; set; }
        public string fechaFinFormato { get; set; }
        public Nullable<long> horometro { get; set; }
    }
    
}
