//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace EntitiesLayer
{
    public partial class viewReporteDynafleet
    {
        private Nullable<double> combustibleAcumuladoAux;

        public int idVehiDetalle { get; set; }
        public string usuario { get; set; }
        public string nombreFlota { get; set; }
        public string vin { get; set; }
        public string evento { get; set; }
        public Nullable<System.DateTime> fechaRegistroGPS { get; set; }
        public string fechaRegistroGPSFormato { get; set; }
        public Nullable<int> velocidad { get; set; }
        public Nullable<decimal> latitud { get; set; }
        public Nullable<decimal> longitud { get; set; }
        public Nullable<decimal> porcentajeCombustible { get; set; }
        public Nullable<long> combustibleAcumulado { get; set; }
        public Nullable<long> odometro { get; set; }
        public Nullable<double> combustibleAcumuladoFormat
        {
            get
            {
                combustibleAcumuladoAux = combustibleAcumulado * (0.00264172);
                return combustibleAcumuladoAux;
            }
            set { combustibleAcumuladoAux = value; }
        }
    }

}
