//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace EntitiesLayer
{
    public partial class viewReporteDynafleet
    {
        public string Usuario { get; set; }
        public string Nombre_Flota { get; set; }
        public string VIN { get; set; }
        public string Evento { get; set; }
        public string Fecha_Hora_evento { get; set; }
        public Nullable<int> Velocidad { get; set; }
        public Nullable<decimal> Latitud { get; set; }
        public Nullable<decimal> Longitud { get; set; }
        public Nullable<decimal> Porc__combustible { get; set; }
        public Nullable<long> Combustible_acumulado { get; set; }
        public Nullable<long> Odometro { get; set; }
    }
    
}
